### PR TITLE
update to pikaday 1.4.0

### PR DESCRIPTION
**Pull request by doits**

### CODE REVIEW

**Comment by christianvuerings** [comment]
@doits just as a fyi, we weren't able to test this ourselves and are no longer using this gem in production.

**Comment by doits** [comment]
I'll see if I stick with it (just started using it) - if yes I can maintain it if you want.

**Comment by doits** [comment]
Works so far for me - release it to rubygems?

**Comment by christianvuerings** [comment]
@doits would suggest you take over the ownership.

Do you already have an account on `rubygems`?
Tried the following but it didn't work:

```
gem owner pikaday-gem -a markus.doits@googlemail.com
Adding markus.doits@googlemail.com: Owner could not be found.
```

**Comment by doits** [comment]
I have, my e-mail there is `markus-gem@stellenticket.de`.

**Comment by christianvuerings** [comment]
@doits you should now be an owner and make the necessary changes:

```
gem owner pikaday-gem -a markus-gem@stellenticket.de
Owner added successfully.
Owners for gem: pikaday-gem
- markus-gem@stellenticket.de
- shacker@birdhouse.org
- yuhung@yuhunglin.com
- vueringschristian@gmail.com
```

**Pull request merged**
